from PyQt6 import QtCore, QtGui, QtWidgets

class car_choose_page(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        Form.setMaximumSize(QtCore.QSize(800, 480))
        self.background = QtWidgets.QGraphicsView(parent=Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.background.setObjectName("background")
        self.text = QtWidgets.QLabel(parent=Form)
        self.text.setGeometry(QtCore.QRect(30, 30, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(24)
        self.text.setFont(font)
        self.text.setStyleSheet("")
        self.text.setLineWidth(0)
        self.text.setMidLineWidth(0)
        self.text.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.text.setIndent(-1)
        self.text.setObjectName("text")
        self.text2 = QtWidgets.QLabel(parent=Form)
        self.text2.setGeometry(QtCore.QRect(30, 77, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.text2.setFont(font)
        self.text2.setStyleSheet("color: #8D8D8D;")
        self.text2.setObjectName("text2")
        self.step_text = QtWidgets.QLabel(parent=Form)
        self.step_text.setGeometry(QtCore.QRect(694, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(28)
        self.step_text.setFont(font)
        self.step_text.setStyleSheet("color: #A6111B")
        self.step_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.step_text.setObjectName("step_text")
        self.accept_button = QtWidgets.QPushButton(parent=Form)
        self.accept_button.setGeometry(QtCore.QRect(268, 384, 264, 66))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.accept_button.setFont(font)
        self.accept_button.setStyleSheet("border-radius: 16;\nbackground-color:#A6111B;\ncolor: white;")
        self.accept_button.setObjectName("accept_button")
        self.back_button = QtWidgets.QPushButton(parent=Form)
        self.back_button.setGeometry(QtCore.QRect(10, 210, 40, 40))
        self.back_button.setStyleSheet("border-radius: 12;\nbackground-color: #A6111B")
        self.back_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Work/SDPO/design/img/play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.back_button.setIcon(icon)
        self.back_button.setIconSize(QtCore.QSize(18, 18))
        self.back_button.setObjectName("back_button")
        self.next_buton = QtWidgets.QPushButton(parent=Form)
        self.next_buton.setGeometry(QtCore.QRect(750, 210, 40, 40))
        self.next_buton.setStyleSheet("border-radius: 12;\nbackground-color: #A6111B")
        self.next_buton.setText("")
        self.next_buton.setIcon(icon)
        self.next_buton.setIconSize(QtCore.QSize(18, 18))
        self.next_buton.setObjectName("next_buton")
        self.car_name_1 = QtWidgets.QLabel(parent=Form)
        self.car_name_1.setGeometry(QtCore.QRect(60, 136, 350, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(17)
        self.car_name_1.setFont(font)
        self.car_name_1.setStyleSheet("")
        self.car_name_1.setLineWidth(0)
        self.car_name_1.setMidLineWidth(0)
        self.car_name_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_name_1.setIndent(-1)
        self.car_name_1.setObjectName("car_name_1")
        self.car_name_2 = QtWidgets.QLabel(parent=Form)
        self.car_name_2.setGeometry(QtCore.QRect(400, 140, 350, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(17)
        self.car_name_2.setFont(font)
        self.car_name_2.setStyleSheet("")
        self.car_name_2.setLineWidth(0)
        self.car_name_2.setMidLineWidth(0)
        self.car_name_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_name_2.setIndent(-1)
        self.car_name_2.setObjectName("car_name_2")
        self.car_number_1 = QtWidgets.QLabel(parent=Form)
        self.car_number_1.setGeometry(QtCore.QRect(60, 171, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_number_1.setFont(font)
        self.car_number_1.setStyleSheet("color:#8C8C8C;")
        self.car_number_1.setLineWidth(0)
        self.car_number_1.setMidLineWidth(0)
        self.car_number_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_number_1.setIndent(-1)
        self.car_number_1.setObjectName("car_number_1")
        self.car_number_2 = QtWidgets.QLabel(parent=Form)
        self.car_number_2.setGeometry(QtCore.QRect(400, 171, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_number_2.setFont(font)
        self.car_number_2.setStyleSheet("color:#8C8C8C;")
        self.car_number_2.setLineWidth(0)
        self.car_number_2.setMidLineWidth(0)
        self.car_number_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_number_2.setIndent(-1)
        self.car_number_2.setObjectName("car_number_2")
        self.car_color_1 = QtWidgets.QLabel(parent=Form)
        self.car_color_1.setGeometry(QtCore.QRect(60, 197, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_color_1.setFont(font)
        self.car_color_1.setStyleSheet("color:#8C8C8C;")
        self.car_color_1.setLineWidth(0)
        self.car_color_1.setMidLineWidth(0)
        self.car_color_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_color_1.setIndent(-1)
        self.car_color_1.setObjectName("car_color_1")
        self.car_color_2 = QtWidgets.QLabel(parent=Form)
        self.car_color_2.setGeometry(QtCore.QRect(400, 197, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_color_2.setFont(font)
        self.car_color_2.setStyleSheet("color:#8C8C8C;")
        self.car_color_2.setLineWidth(0)
        self.car_color_2.setMidLineWidth(0)
        self.car_color_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_color_2.setIndent(-1)
        self.car_color_2.setObjectName("car_color_2")
        self.car_count_1 = QtWidgets.QLabel(parent=Form)
        self.car_count_1.setGeometry(QtCore.QRect(60, 223, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_count_1.setFont(font)
        self.car_count_1.setStyleSheet("color:#8C8C8C;")
        self.car_count_1.setLineWidth(0)
        self.car_count_1.setMidLineWidth(0)
        self.car_count_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_count_1.setIndent(-1)
        self.car_count_1.setObjectName("car_count_1")
        self.car_count_2 = QtWidgets.QLabel(parent=Form)
        self.car_count_2.setGeometry(QtCore.QRect(400, 223, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_count_2.setFont(font)
        self.car_count_2.setStyleSheet("color:#8C8C8C;")
        self.car_count_2.setLineWidth(0)
        self.car_count_2.setMidLineWidth(0)
        self.car_count_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_count_2.setIndent(-1)
        self.car_count_2.setObjectName("car_count_2")
        self.car_number_data_1 = QtWidgets.QLabel(parent=Form)
        self.car_number_data_1.setGeometry(QtCore.QRect(130, 171, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_number_data_1.setFont(font)
        self.car_number_data_1.setStyleSheet("color:#2E2E2E;")
        self.car_number_data_1.setLineWidth(0)
        self.car_number_data_1.setMidLineWidth(0)
        self.car_number_data_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_number_data_1.setIndent(-1)
        self.car_number_data_1.setObjectName("car_number_data_1")
        self.car_number_data_2 = QtWidgets.QLabel(parent=Form)
        self.car_number_data_2.setGeometry(QtCore.QRect(470, 171, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_number_data_2.setFont(font)
        self.car_number_data_2.setStyleSheet("color:#2E2E2E;")
        self.car_number_data_2.setLineWidth(0)
        self.car_number_data_2.setMidLineWidth(0)
        self.car_number_data_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_number_data_2.setIndent(-1)
        self.car_number_data_2.setObjectName("car_number_data_2")
        self.car_color_data_1 = QtWidgets.QLabel(parent=Form)
        self.car_color_data_1.setGeometry(QtCore.QRect(115, 197, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_color_data_1.setFont(font)
        self.car_color_data_1.setStyleSheet("color:#2E2E2E;")
        self.car_color_data_1.setLineWidth(0)
        self.car_color_data_1.setMidLineWidth(0)
        self.car_color_data_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_color_data_1.setIndent(-1)
        self.car_color_data_1.setObjectName("car_color_data_1")
        self.car_color_data_2 = QtWidgets.QLabel(parent=Form)
        self.car_color_data_2.setGeometry(QtCore.QRect(455, 197, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_color_data_2.setFont(font)
        self.car_color_data_2.setStyleSheet("color:#2E2E2E;")
        self.car_color_data_2.setLineWidth(0)
        self.car_color_data_2.setMidLineWidth(0)
        self.car_color_data_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_color_data_2.setIndent(-1)
        self.car_color_data_2.setObjectName("car_color_data_2")
        self.car_count_data_1 = QtWidgets.QLabel(parent=Form)
        self.car_count_data_1.setGeometry(QtCore.QRect(135, 223, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_count_data_1.setFont(font)
        self.car_count_data_1.setStyleSheet("color:#2E2E2E;")
        self.car_count_data_1.setLineWidth(0)
        self.car_count_data_1.setMidLineWidth(0)
        self.car_count_data_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_count_data_1.setIndent(-1)
        self.car_count_data_1.setObjectName("car_count_data_1")
        self.car_count_data_2 = QtWidgets.QLabel(parent=Form)
        self.car_count_data_2.setGeometry(QtCore.QRect(475, 223, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        self.car_count_data_2.setFont(font)
        self.car_count_data_2.setStyleSheet("color:#2E2E2E;")
        self.car_count_data_2.setLineWidth(0)
        self.car_count_data_2.setMidLineWidth(0)
        self.car_count_data_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.car_count_data_2.setIndent(-1)
        self.car_count_data_2.setObjectName("car_count_data_2")
        self.car_img_1 = QtWidgets.QPushButton(parent=Form)
        self.car_img_1.setGeometry(QtCore.QRect(266, 136, 109, 109))
        self.car_img_1.setStyleSheet("border-radius: 12;\nbackground-color: #E4E4E4;")
        self.car_img_1.setText("")
        self.car_img_1.setIconSize(QtCore.QSize(18, 18))
        self.car_img_1.setObjectName("car_img_1")
        self.car_img_2 = QtWidgets.QPushButton(parent=Form)
        self.car_img_2.setGeometry(QtCore.QRect(611, 136, 109, 109))
        self.car_img_2.setStyleSheet("border-radius: 12;\nbackground-color: #E4E4E4;")
        self.car_img_2.setText("")
        self.car_img_2.setIconSize(QtCore.QSize(18, 18))
        self.car_img_2.setObjectName("car_img_2")
        self.choose_button_1 = QtWidgets.QPushButton(parent=Form)
        self.choose_button_1.setGeometry(QtCore.QRect(60, 260, 315, 66))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.choose_button_1.setFont(font)
        self.choose_button_1.setStyleSheet("border-radius: 16;\nbackground-color:#F6F6F6;\ncolor: black;")
        self.choose_button_1.setObjectName("choose_button_1")
        self.choose_button_2 = QtWidgets.QPushButton(parent=Form)
        self.choose_button_2.setGeometry(QtCore.QRect(405, 260, 315, 66))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.choose_button_2.setFont(font)
        self.choose_button_2.setStyleSheet("border-radius: 16;\nbackground-color:#F6F6F6;\ncolor: black;")
        self.choose_button_2.setObjectName("choose_button_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.text.setText(_translate("Form", "Выберите автомобиль"))
        self.text2.setText(_translate("Form", "Выберите автомобиль из списка, листая вправо"))
        self.step_text.setText(_translate("Form", "2/3"))
        self.accept_button.setText(_translate("Form", "Продолжить"))
        self.car_name_1.setText(_translate("Form", "Лада Гранта 1"))
        self.car_name_2.setText(_translate("Form", "Лада Гранта 2"))
        self.car_number_1.setText(_translate("Form", "Номер:"))
        self.car_number_2.setText(_translate("Form", "Номер:"))
        self.car_color_1.setText(_translate("Form", "Цвет:"))
        self.car_color_2.setText(_translate("Form", "Цвет:"))
        self.car_count_1.setText(_translate("Form", "Пробег:"))
        self.car_count_2.setText(_translate("Form", "Пробег:"))
        self.car_number_data_1.setText(_translate("Form", "A111AA"))
        self.car_number_data_2.setText(_translate("Form", "Б222ББ"))
        self.car_color_data_1.setText(_translate("Form", "Красный"))
        self.car_color_data_2.setText(_translate("Form", "Синий"))
        self.car_count_data_1.setText(_translate("Form", "123456 км"))
        self.car_count_data_2.setText(_translate("Form", "654321 км"))
        self.choose_button_1.setText(_translate("Form", "Выбрать"))
        self.choose_button_2.setText(_translate("Form", "Выбрать"))
