from PyQt6 import QtCore, QtGui, QtWidgets

class second_step_page(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        Form.setMinimumSize(QtCore.QSize(800, 480))
        Form.setMaximumSize(QtCore.QSize(800, 480))
        self.background = QtWidgets.QGraphicsView(parent=Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.background.setStyleSheet("border: 0;")
        self.background.setObjectName("background")
        self.text = QtWidgets.QLabel(parent=Form)
        self.text.setGeometry(QtCore.QRect(35, 30, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(24)
        self.text.setFont(font)
        self.text.setStyleSheet("")
        self.text.setLineWidth(0)
        self.text.setMidLineWidth(0)
        self.text.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.text.setIndent(-1)
        self.text.setObjectName("text")
        self.editinfoText = QtWidgets.QLabel(parent=Form)
        self.editinfoText.setGeometry(QtCore.QRect(35, 77, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.editinfoText.setFont(font)
        self.editinfoText.setStyleSheet("color: #8D8D8D;")
        self.editinfoText.setObjectName("editinfoText")
        self.step_text = QtWidgets.QLabel(parent=Form)
        self.step_text.setGeometry(QtCore.QRect(700, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(28)
        self.step_text.setFont(font)
        self.step_text.setStyleSheet("color: #A6111B")
        self.step_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.step_text.setObjectName("step_text")
        self.back_button = QtWidgets.QPushButton(parent=Form)
        self.back_button.setGeometry(QtCore.QRect(303, 384, 193, 66))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet("color: #A6111B;\nbackground: #FFE0E3;\nborder-radius: 16px;")
        self.back_button.setObjectName("back_button")
        self.report_heal_button = QtWidgets.QPushButton(parent=Form)
        self.report_heal_button.setGeometry(QtCore.QRect(408, 197, 362, 87))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        self.report_heal_button.setFont(font)
        self.report_heal_button.setStyleSheet("color: #DE1E1E;\nbackground: #FFF4F4;\nborder-radius: 16px;")
        self.report_heal_button.setObjectName("report_heal_button")
        self.skip_step_button = QtWidgets.QPushButton(parent=Form)
        self.skip_step_button.setGeometry(QtCore.QRect(30, 200, 362, 87))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        self.skip_step_button.setFont(font)
        self.skip_step_button.setStyleSheet("color: #11A631;\nbackground: #F4FFF6;\nborder-radius: 16px;")
        self.skip_step_button.setObjectName("skip_step_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.text.setText(_translate("Form", "Жалобы на здоровье"))
        self.editinfoText.setText(_translate("Form", "Выберите есть ли у вас жалобы на здоровье, или их нет"))
        self.step_text.setText(_translate("Form", "2/5"))
        self.back_button.setText(_translate("Form", "Назад"))
        self.report_heal_button.setText(_translate("Form", "Жалобы есть"))
        self.skip_step_button.setText(_translate("Form", "Жалоб нет"))
