from PyQt6 import QtCore, QtGui, QtWidgets

class type_report_page(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
		Form.resize(800, 480)
		Form.setMinimumSize(QtCore.QSize(800, 480))
		Form.setMaximumSize(QtCore.QSize(800, 480))
		self.background = QtWidgets.QGraphicsView(parent=Form)
		self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
		self.background.setStyleSheet("border: 0;")
		self.background.setObjectName("background")
		self.text = QtWidgets.QLabel(parent=Form)
		self.text.setGeometry(QtCore.QRect(30, 30, 341, 41))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(24)
		self.text.setFont(font)
		self.text.setStyleSheet("")
		self.text.setLineWidth(0)
		self.text.setMidLineWidth(0)
		self.text.setTextFormat(QtCore.Qt.TextFormat.AutoText)
		self.text.setIndent(-1)
		self.text.setObjectName("text")
		self.step_text = QtWidgets.QLabel(parent=Form)
		self.step_text.setGeometry(QtCore.QRect(689, 30, 61, 31))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(28)
		self.step_text.setFont(font)
		self.step_text.setStyleSheet("color: #A6111B")
		self.step_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		self.step_text.setObjectName("step_text")
		self.text2 = QtWidgets.QLabel(parent=Form)
		self.text2.setGeometry(QtCore.QRect(30, 77, 491, 31))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(13)
		self.text2.setFont(font)
		self.text2.setStyleSheet("color: #8D8D8D;")
		self.text2.setObjectName("text2")
		self.back_button = QtWidgets.QPushButton(parent=Form)
		self.back_button.setGeometry(QtCore.QRect(303, 384, 193, 66))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(16)
		self.back_button.setFont(font)
		self.back_button.setStyleSheet("color: #A6111B;\nbackground: #FFE0E3;\nborder-radius: 16px;")
		self.back_button.setObjectName("back_button")
		self.backache_button = QtWidgets.QPushButton(parent=Form)
		self.backache_button.setGeometry(QtCore.QRect(30, 145, 236, 87))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(16)
		font.setBold(False)
		font.setWeight(50)
		self.backache_button.setFont(font)
		self.backache_button.setStyleSheet("border-radius: 16;\nbackground-color: #F6F6F6")
		self.backache_button.setObjectName("backache_button")
		self.stomackache_button = QtWidgets.QPushButton(parent=Form)
		self.stomackache_button.setGeometry(QtCore.QRect(282, 145, 236, 87))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(16)
		font.setBold(False)
		font.setWeight(50)
		self.stomackache_button.setFont(font)
		self.stomackache_button.setStyleSheet("border-radius: 16;\nbackground-color: #F6F6F6")
		self.stomackache_button.setObjectName("stomackache_button")
		self.eyeache_button = QtWidgets.QPushButton(parent=Form)
		self.eyeache_button.setGeometry(QtCore.QRect(534, 145, 236, 87))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(16)
		font.setBold(False)
		font.setWeight(50)
		self.eyeache_button.setFont(font)
		self.eyeache_button.setStyleSheet("border-radius: 16;\nbackground-color: #F6F6F6")
		self.eyeache_button.setObjectName("eyeache_button")
		self.handache_button = QtWidgets.QPushButton(parent=Form)
		self.handache_button.setGeometry(QtCore.QRect(30, 248, 173, 87))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(16)
		font.setBold(False)
		font.setWeight(50)
		self.handache_button.setFont(font)
		self.handache_button.setStyleSheet("border-radius: 16;\nbackground-color: #F6F6F6")
		self.handache_button.setObjectName("handache_button")
		self.headache_button = QtWidgets.QPushButton(parent=Form)
		self.headache_button.setGeometry(QtCore.QRect(219, 248, 173, 87))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(16)
		font.setBold(False)
		font.setWeight(50)
		self.headache_button.setFont(font)
		self.headache_button.setStyleSheet("border-radius: 16;\nbackground-color: #F6F6F6")
		self.headache_button.setObjectName("headache_button")
		self.teethache_button = QtWidgets.QPushButton(parent=Form)
		self.teethache_button.setGeometry(QtCore.QRect(408, 248, 173, 87))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(16)
		font.setBold(False)
		font.setWeight(50)
		self.teethache_button.setFont(font)
		self.teethache_button.setStyleSheet("border-radius: 16;\nbackground-color: #F6F6F6")
		self.teethache_button.setObjectName("teethache_button")
		self.other_button = QtWidgets.QPushButton(parent=Form)
		self.other_button.setGeometry(QtCore.QRect(597, 248, 173, 87))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(16)
		font.setBold(False)
		font.setWeight(50)
		self.other_button.setFont(font)
		self.other_button.setStyleSheet("border-radius: 16;\nbackground-color: #F6F6F6")
		self.other_button.setObjectName("other_button")

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		_translate = QtCore.QCoreApplication.translate
		Form.setWindowTitle(_translate("Form", "Form"))
		self.text.setText(_translate("Form", "Жалобы на здоровье"))
		self.step_text.setText(_translate("Form", "2/5"))
		self.text2.setText(_translate("Form", "Выберите есть ли у вас жалобы на здоровье, или их нет"))
		self.back_button.setText(_translate("Form", "Назад"))
		self.backache_button.setText(_translate("Form", "Боль в спине"))
		self.stomackache_button.setText(_translate("Form", "Боль в животе"))
		self.eyeache_button.setText(_translate("Form", "Боль в глазах"))
		self.handache_button.setText(_translate("Form", "Боль в руках"))
		self.headache_button.setText(_translate("Form", "Головная боль"))
		self.teethache_button.setText(_translate("Form", "Зубная боль"))
		self.other_button.setText(_translate("Form", "Другое"))
