from PyQt6 import QtCore, QtGui, QtWidgets

class authorization_page(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
		Form.resize(800, 480)
		self.key_zero = QtWidgets.QPushButton(Form)
		self.key_zero.setGeometry(QtCore.QRect(30, 374, 181, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_zero.setFont(font)
		self.key_zero.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_zero.setObjectName("key_zero")
		self.num_field = QtWidgets.QLabel(Form)
		self.num_field.setGeometry(QtCore.QRect(416, 211, 365, 66))
		self.num_field.setStyleSheet("background: #FFFFFF;\n\nborder: 1px solid #CDCDCD;\nborder-radius: 16px;\n\nfont-family: \'Inter\';\nfont-style: normal;\nfont-weight: 400;\nfont-size: 22px;\n\ncolor: #8D8D8D;\n")
		self.num_field.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		self.num_field.setObjectName("num_field")
		self.key_three = QtWidgets.QPushButton(Form)
		self.key_three.setGeometry(QtCore.QRect(279, 143, 118, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_three.setFont(font)
		self.key_three.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_three.setObjectName("key_three")
		self.clear_button = QtWidgets.QPushButton(Form)
		self.clear_button.setGeometry(QtCore.QRect(217, 374, 181, 71))
		font = QtGui.QFont()
		font.setPointSize(40)
		self.clear_button.setFont(font)
		self.clear_button.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.clear_button.setText("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("pagesCode/img/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
		self.clear_button.setIcon(icon)
		self.clear_button.setIconSize(QtCore.QSize(50, 80))
		self.clear_button.setObjectName("clear_button")
		self.key_one = QtWidgets.QPushButton(Form)
		self.key_one.setGeometry(QtCore.QRect(30, 143, 118, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_one.setFont(font)
		self.key_one.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_one.setObjectName("key_one")
		self.key_two = QtWidgets.QPushButton(Form)
		self.key_two.setGeometry(QtCore.QRect(154, 143, 118, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_two.setFont(font)
		self.key_two.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_two.setObjectName("key_two")
		self.key_eight = QtWidgets.QPushButton(Form)
		self.key_eight.setGeometry(QtCore.QRect(154, 297, 118, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_eight.setFont(font)
		self.key_eight.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_eight.setObjectName("key_eight")
		self.key_nine = QtWidgets.QPushButton(Form)
		self.key_nine.setGeometry(QtCore.QRect(279, 297, 118, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_nine.setFont(font)
		self.key_nine.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_nine.setObjectName("key_nine")
		self.background = QtWidgets.QGraphicsView(Form)
		self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
		self.background.setStyleSheet("border: 0;")
		self.background.setObjectName("background")
		self.key_seven = QtWidgets.QPushButton(Form)
		self.key_seven.setGeometry(QtCore.QRect(30, 297, 118, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_seven.setFont(font)
		self.key_seven.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_seven.setObjectName("key_seven")
		self.error_text = QtWidgets.QLabel(Form)
		self.error_text.setGeometry(QtCore.QRect(220, 68, 361, 31))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(22)
		font.setItalic(False)
		self.error_text.setFont(font)
		self.error_text.setStyleSheet("color: red;")
		self.error_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		self.error_text.setObjectName("error_text")
		self.background_two = QtWidgets.QGraphicsView(Form)
		self.background_two.setGeometry(QtCore.QRect(0, 116, 800, 364))
		self.background_two.setStyleSheet("background-color: #F5F5F5;\nborder: 0")
		self.background_two.setObjectName("background_two")
		self.key_six = QtWidgets.QPushButton(Form)
		self.key_six.setGeometry(QtCore.QRect(279, 220, 118, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_six.setFont(font)
		self.key_six.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_six.setObjectName("key_six")
		self.key_five = QtWidgets.QPushButton(Form)
		self.key_five.setGeometry(QtCore.QRect(154, 220, 118, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_five.setFont(font)
		self.key_five.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_five.setObjectName("key_five")
		self.enter_button = QtWidgets.QPushButton(Form)
		self.enter_button.setGeometry(QtCore.QRect(497, 305, 203, 64))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(22)
		font.setBold(False)
		font.setWeight(50)
		self.enter_button.setFont(font)
		self.enter_button.setStyleSheet("border-radius: 16;\nbackground-color:#A6111B;\ncolor: white;")
		self.enter_button.setObjectName("enter_button")
		self.text = QtWidgets.QLabel(Form)
		self.text.setGeometry(QtCore.QRect(228, 12, 341, 48))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.text.setFont(font)
		self.text.setObjectName("text")
		self.key_four = QtWidgets.QPushButton(Form)
		self.key_four.setGeometry(QtCore.QRect(30, 220, 118, 71))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(40)
		font.setBold(False)
		font.setWeight(50)
		self.key_four.setFont(font)
		self.key_four.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
		self.key_four.setObjectName("key_four")
		self.background.raise_()
		self.background_two.raise_()
		self.key_zero.raise_()
		self.num_field.raise_()
		self.key_three.raise_()
		self.clear_button.raise_()
		self.key_one.raise_()
		self.key_two.raise_()
		self.key_eight.raise_()
		self.key_nine.raise_()
		self.key_seven.raise_()
		self.error_text.raise_()
		self.key_six.raise_()
		self.key_five.raise_()
		self.enter_button.raise_()
		self.text.raise_()
		self.key_four.raise_()
		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

		self.add_functions()

	def retranslateUi(self, Form):
		_translate = QtCore.QCoreApplication.translate
		Form.setWindowTitle(_translate("Form", "Form"))
		self.key_zero.setText(_translate("Form", "0"))
		self.num_field.setText(_translate("Form", "Логин/Номер телефона"))
		self.key_three.setText(_translate("Form", "3"))
		self.key_one.setText(_translate("Form", "1"))
		self.key_two.setText(_translate("Form", "2"))
		self.key_eight.setText(_translate("Form", "8"))
		self.key_nine.setText(_translate("Form", "9"))
		self.key_seven.setText(_translate("Form", "7"))
		self.error_text.setText(_translate("Form", ""))
		self.key_six.setText(_translate("Form", "6"))
		self.key_five.setText(_translate("Form", "5"))
		self.enter_button.setText(_translate("Form", "Войти"))
		self.text.setText(_translate("Form", "Авторизация"))
		self.key_four.setText(_translate("Form", "4"))

	def add_functions(self):
		self.key_zero.clicked.connect(lambda: self.write_number(self.key_zero.text()))
		self.key_one.clicked.connect(lambda: self.write_number(self.key_one.text()))
		self.key_two.clicked.connect(lambda: self.write_number(self.key_two.text()))
		self.key_three.clicked.connect(lambda: self.write_number(self.key_three.text()))
		self.key_four.clicked.connect(lambda: self.write_number(self.key_four.text()))
		self.key_five.clicked.connect(lambda: self.write_number(self.key_five.text()))
		self.key_six.clicked.connect(lambda: self.write_number(self.key_six.text()))
		self.key_seven.clicked.connect(lambda: self.write_number(self.key_seven.text()))
		self.key_eight.clicked.connect(lambda: self.write_number(self.key_eight.text()))
		self.key_nine.clicked.connect(lambda: self.write_number(self.key_nine.text()))
		self.clear_button.clicked.connect(self.clear_input)
		
	def write_number(self, number):
		self.num_field.setStyleSheet(f"background: #FFFFFF;\n\nborder: 1px solid #CDCDCD;\nborder-radius: 16px;\n\nfont-family: \'Inter\';\nfont-style: normal;\nfont-weight: 400;\nfont-size: 32px;\n\ncolor: #141414;\n")
		if self.num_field.text() == 'Логин/Номер телефона':
			self.num_field.setText(number)
		else:
			self.num_field.setText(self.num_field.text()+number)

	def clear_input(self):
		self.error_text.setText("")
		if self.num_field.text() != 'Логин/Номер телефона':
			if len(self.num_field.text())-1 == 0:
				self.num_field.setStyleSheet(f"background: #FFFFFF;\n\nborder: 1px solid #CDCDCD;\nborder-radius: 16px;\n\nfont-family: \'Inter\';\nfont-style: normal;\nfont-weight: 400;\nfont-size: 22px;\n\ncolor: #8D8D8D;\n")
				self.num_field.setText('Логин/Номер телефона')
			else:
				self.num_field.setText(self.num_field.text()[:-1])