from PyQt6 import QtCore, QtGui, QtWidgets

class instruct_audio_page(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
		Form.resize(800, 480)
		Form.setMaximumSize(QtCore.QSize(800, 480))
		self.background = QtWidgets.QGraphicsView(parent=Form)
		self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
		self.background.setObjectName("background")
		self.play_audio_first_button = QtWidgets.QPushButton(parent=Form)
		self.play_audio_first_button.setGeometry(QtCore.QRect(30, 165, 38, 38))
		self.play_audio_first_button.setStyleSheet("border-radius: 12;\nbackground-color: #A6111B")
		self.play_audio_first_button.setText("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("D:/Work/SDPO/design/img/play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
		self.play_audio_first_button.setIcon(icon)
		self.play_audio_first_button.setIconSize(QtCore.QSize(18, 18))
		self.play_audio_first_button.setObjectName("play_audio_first_button")
		self.play_audio_third_button = QtWidgets.QPushButton(parent=Form)
		self.play_audio_third_button.setGeometry(QtCore.QRect(30, 223, 38, 38))
		self.play_audio_third_button.setStyleSheet("border-radius: 12;\nbackground-color: #A6111B")
		self.play_audio_third_button.setText("")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(".\\pagesDesign\\img/play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
		self.play_audio_third_button.setIcon(icon1)
		self.play_audio_third_button.setIconSize(QtCore.QSize(18, 18))
		self.play_audio_third_button.setObjectName("play_audio_third_button")
		self.play_audio_fifth_button = QtWidgets.QPushButton(parent=Form)
		self.play_audio_fifth_button.setGeometry(QtCore.QRect(30, 281, 38, 38))
		self.play_audio_fifth_button.setStyleSheet("border-radius: 12;\nbackground-color: #A6111B")
		self.play_audio_fifth_button.setText("")
		self.play_audio_fifth_button.setIcon(icon1)
		self.play_audio_fifth_button.setIconSize(QtCore.QSize(18, 18))
		self.play_audio_fifth_button.setObjectName("play_audio_fifth_button")
		self.first_line = QtWidgets.QGraphicsView(parent=Form)
		self.first_line.setGeometry(QtCore.QRect(80, 195, 286, 5))
		self.first_line.setStyleSheet("background-color: #A6111B")
		self.first_line.setObjectName("first_line")
		self.third_line = QtWidgets.QGraphicsView(parent=Form)
		self.third_line.setGeometry(QtCore.QRect(80, 253, 286, 5))
		self.third_line.setStyleSheet("background-color: #A6111B")
		self.third_line.setObjectName("third_line")
		self.fifth_line = QtWidgets.QGraphicsView(parent=Form)
		self.fifth_line.setGeometry(QtCore.QRect(80, 311, 286, 5))
		self.fifth_line.setStyleSheet("background-color: #A6111B")
		self.fifth_line.setObjectName("fifth_line")
		self.play_audio_second_button = QtWidgets.QPushButton(parent=Form)
		self.play_audio_second_button.setGeometry(QtCore.QRect(434, 165, 38, 38))
		self.play_audio_second_button.setStyleSheet("border-radius: 12;\nbackground-color: #A6111B")
		self.play_audio_second_button.setText("")
		self.play_audio_second_button.setIcon(icon1)
		self.play_audio_second_button.setIconSize(QtCore.QSize(18, 18))
		self.play_audio_second_button.setObjectName("play_audio_second_button")
		self.sixth_line = QtWidgets.QGraphicsView(parent=Form)
		self.sixth_line.setGeometry(QtCore.QRect(484, 311, 286, 5))
		self.sixth_line.setStyleSheet("background-color: #A6111B")
		self.sixth_line.setObjectName("sixth_line")
		self.play_audio_sixth_button = QtWidgets.QPushButton(parent=Form)
		self.play_audio_sixth_button.setGeometry(QtCore.QRect(434, 281, 38, 38))
		self.play_audio_sixth_button.setStyleSheet("border-radius: 12;\nbackground-color: #A6111B")
		self.play_audio_sixth_button.setText("")
		self.play_audio_sixth_button.setIcon(icon1)
		self.play_audio_sixth_button.setIconSize(QtCore.QSize(18, 18))
		self.play_audio_sixth_button.setObjectName("play_audio_sixth_button")
		self.play_audio_fourth_button = QtWidgets.QPushButton(parent=Form)
		self.play_audio_fourth_button.setGeometry(QtCore.QRect(434, 223, 38, 38))
		self.play_audio_fourth_button.setStyleSheet("border-radius: 12;\nbackground-color: #A6111B")
		self.play_audio_fourth_button.setText("")
		self.play_audio_fourth_button.setIcon(icon1)
		self.play_audio_fourth_button.setIconSize(QtCore.QSize(18, 18))
		self.play_audio_fourth_button.setObjectName("play_audio_fourth_button")
		self.second_line = QtWidgets.QGraphicsView(parent=Form)
		self.second_line.setGeometry(QtCore.QRect(484, 195, 286, 5))
		self.second_line.setStyleSheet("background-color: #A6111B")
		self.second_line.setObjectName("second_line")
		self.fourth_line = QtWidgets.QGraphicsView(parent=Form)
		self.fourth_line.setGeometry(QtCore.QRect(484, 253, 286, 5))
		self.fourth_line.setStyleSheet("background-color: #A6111B")
		self.fourth_line.setObjectName("fourth_line")
		self.play_audio_first_text = QtWidgets.QLabel(parent=Form)
		self.play_audio_first_text.setGeometry(QtCore.QRect(80, 170, 291, 20))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(14)
		font.setItalic(False)
		self.play_audio_first_text.setFont(font)
		self.play_audio_first_text.setStyleSheet("color: black;")
		self.play_audio_first_text.setObjectName("play_audio_first_text")
		self.play_audio_third_text = QtWidgets.QLabel(parent=Form)
		self.play_audio_third_text.setGeometry(QtCore.QRect(80, 228, 291, 20))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(14)
		font.setItalic(False)
		self.play_audio_third_text.setFont(font)
		self.play_audio_third_text.setStyleSheet("color: black;")
		self.play_audio_third_text.setObjectName("play_audio_third_text")
		self.play_audio_fifth_text = QtWidgets.QLabel(parent=Form)
		self.play_audio_fifth_text.setGeometry(QtCore.QRect(80, 286, 291, 20))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(14)
		font.setItalic(False)
		self.play_audio_fifth_text.setFont(font)
		self.play_audio_fifth_text.setStyleSheet("color: black;")
		self.play_audio_fifth_text.setObjectName("play_audio_fifth_text")
		self.play_audio_second_text = QtWidgets.QLabel(parent=Form)
		self.play_audio_second_text.setGeometry(QtCore.QRect(484, 170, 291, 20))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(14)
		font.setItalic(False)
		self.play_audio_second_text.setFont(font)
		self.play_audio_second_text.setStyleSheet("color: black;")
		self.play_audio_second_text.setObjectName("play_audio_second_text")
		self.play_audio_sixth_text = QtWidgets.QLabel(parent=Form)
		self.play_audio_sixth_text.setGeometry(QtCore.QRect(484, 286, 291, 20))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(14)
		font.setItalic(False)
		self.play_audio_sixth_text.setFont(font)
		self.play_audio_sixth_text.setStyleSheet("color: black;")
		self.play_audio_sixth_text.setObjectName("play_audio_sixth_text")
		self.play_audio_fourth_text = QtWidgets.QLabel(parent=Form)
		self.play_audio_fourth_text.setGeometry(QtCore.QRect(484, 228, 291, 20))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(14)
		font.setItalic(False)
		self.play_audio_fourth_text.setFont(font)
		self.play_audio_fourth_text.setStyleSheet("color: black;")
		self.play_audio_fourth_text.setObjectName("play_audio_fourth_text")
		self.text = QtWidgets.QLabel(parent=Form)
		self.text.setGeometry(QtCore.QRect(30, 30, 201, 41))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(24)
		self.text.setFont(font)
		self.text.setStyleSheet("")
		self.text.setLineWidth(0)
		self.text.setMidLineWidth(0)
		self.text.setTextFormat(QtCore.Qt.TextFormat.AutoText)
		self.text.setIndent(-1)
		self.text.setObjectName("text")
		self.text2 = QtWidgets.QLabel(parent=Form)
		self.text2.setGeometry(QtCore.QRect(30, 77, 491, 31))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(13)
		self.text2.setFont(font)
		self.text2.setStyleSheet("color: #8D8D8D;")
		self.text2.setObjectName("text2")
		self.step_text = QtWidgets.QLabel(parent=Form)
		self.step_text.setGeometry(QtCore.QRect(694, 30, 61, 31))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(28)
		self.step_text.setFont(font)
		self.step_text.setStyleSheet("color: #A6111B")
		self.step_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		self.step_text.setObjectName("step_text")
		self.accept_button = QtWidgets.QPushButton(parent=Form)
		self.accept_button.setGeometry(QtCore.QRect(183, 384, 434, 66))
		font = QtGui.QFont()
		font.setFamily("Inter")
		font.setPointSize(16)
		font.setBold(False)
		font.setWeight(50)
		self.accept_button.setFont(font)
		self.accept_button.setStyleSheet("border-radius: 16;\nbackground-color:#A6111B;\ncolor: white;")
		self.accept_button.setObjectName("accept_button")

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		_translate = QtCore.QCoreApplication.translate
		Form.setWindowTitle(_translate("Form", "Form"))
		self.play_audio_first_text.setText(_translate("Form", "File name"))
		self.play_audio_third_text.setText(_translate("Form", "File name"))
		self.play_audio_fifth_text.setText(_translate("Form", "File name"))
		self.play_audio_second_text.setText(_translate("Form", "File name"))
		self.play_audio_sixth_text.setText(_translate("Form", "File name"))
		self.play_audio_fourth_text.setText(_translate("Form", "File name"))
		self.text.setText(_translate("Form", "Инструктаж"))
		self.text2.setText(_translate("Form", "Прослушайте инструктаж по БДД"))
		self.step_text.setText(_translate("Form", "1/3"))
		self.accept_button.setText(_translate("Form", "Я уже прослушал, подписать"))
