from PyQt6 import QtCore, QtGui, QtWidgets

class car_data_page(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        Form.setMinimumSize(QtCore.QSize(800, 480))
        Form.setMaximumSize(QtCore.QSize(800, 480))
        self.background = QtWidgets.QGraphicsView(parent=Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.background.setStyleSheet("border: 0;")
        self.background.setObjectName("background")
        self.text = QtWidgets.QLabel(parent=Form)
        self.text.setGeometry(QtCore.QRect(35, 30, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(24)
        self.text.setFont(font)
        self.text.setStyleSheet("")
        self.text.setLineWidth(0)
        self.text.setMidLineWidth(0)
        self.text.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.text.setIndent(-1)
        self.text.setObjectName("text")
        self.car_name_field = QtWidgets.QLabel(parent=Form)
        self.car_name_field.setGeometry(QtCore.QRect(35, 77, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.car_name_field.setFont(font)
        self.car_name_field.setStyleSheet("color: #A6111B;")
        self.car_name_field.setObjectName("car_name_field")
        self.step_text = QtWidgets.QLabel(parent=Form)
        self.step_text.setGeometry(QtCore.QRect(700, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(28)
        self.step_text.setFont(font)
        self.step_text.setStyleSheet("color: #A6111B")
        self.step_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.step_text.setObjectName("step_text")
        self.key_zero = QtWidgets.QPushButton(parent=Form)
        self.key_zero.setGeometry(QtCore.QRect(31, 374, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_zero.setFont(font)
        self.key_zero.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_zero.setObjectName("key_zero")
        self.key_nine = QtWidgets.QPushButton(parent=Form)
        self.key_nine.setGeometry(QtCore.QRect(280, 297, 118, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_nine.setFont(font)
        self.key_nine.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_nine.setObjectName("key_nine")
        self.key_five = QtWidgets.QPushButton(parent=Form)
        self.key_five.setGeometry(QtCore.QRect(155, 220, 118, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_five.setFont(font)
        self.key_five.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_five.setObjectName("key_five")
        self.key_seven = QtWidgets.QPushButton(parent=Form)
        self.key_seven.setGeometry(QtCore.QRect(31, 297, 118, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_seven.setFont(font)
        self.key_seven.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_seven.setObjectName("key_seven")
        self.key_eight = QtWidgets.QPushButton(parent=Form)
        self.key_eight.setGeometry(QtCore.QRect(155, 297, 118, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_eight.setFont(font)
        self.key_eight.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_eight.setObjectName("key_eight")
        self.background2 = QtWidgets.QGraphicsView(parent=Form)
        self.background2.setGeometry(QtCore.QRect(1, 116, 800, 364))
        self.background2.setStyleSheet("background-color: #F5F5F5;\nborder: 0")
        self.background2.setObjectName("background2")
        self.key_two = QtWidgets.QPushButton(parent=Form)
        self.key_two.setGeometry(QtCore.QRect(155, 143, 118, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_two.setFont(font)
        self.key_two.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_two.setObjectName("key_two")
        self.clear_button = QtWidgets.QPushButton(parent=Form)
        self.clear_button.setGeometry(QtCore.QRect(218, 374, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.clear_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Work/SDPO/design/img/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clear_button.setIcon(icon)
        self.clear_button.setIconSize(QtCore.QSize(50, 80))
        self.clear_button.setObjectName("clear_button")
        self.key_four = QtWidgets.QPushButton(parent=Form)
        self.key_four.setGeometry(QtCore.QRect(31, 220, 118, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_four.setFont(font)
        self.key_four.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_four.setObjectName("key_four")
        self.key_one = QtWidgets.QPushButton(parent=Form)
        self.key_one.setGeometry(QtCore.QRect(31, 143, 118, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_one.setFont(font)
        self.key_one.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_one.setObjectName("key_one")
        self.key_three = QtWidgets.QPushButton(parent=Form)
        self.key_three.setGeometry(QtCore.QRect(280, 143, 118, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_three.setFont(font)
        self.key_three.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_three.setObjectName("key_three")
        self.key_six = QtWidgets.QPushButton(parent=Form)
        self.key_six.setGeometry(QtCore.QRect(280, 220, 118, 71))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.key_six.setFont(font)
        self.key_six.setStyleSheet("border-radius: 16;\nbackground-color: rgb(228, 228, 228)")
        self.key_six.setObjectName("key_six")
        self.next_step_page = QtWidgets.QPushButton(parent=Form)
        self.next_step_page.setGeometry(QtCore.QRect(510, 350, 203, 64))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.next_step_page.setFont(font)
        self.next_step_page.setStyleSheet("border-radius: 16;\nbackground-color:#A6111B;\ncolor: white;")
        self.next_step_page.setObjectName("next_step_page")
        self.mileage_field = QtWidgets.QPushButton(parent=Form)
        self.mileage_field.setGeometry(QtCore.QRect(420, 169, 365, 66))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mileage_field.setFont(font)
        self.mileage_field.setStyleSheet("background: #FFFFFF;\n\nborder: 1px solid #CDCDCD;\nborder-radius: 16px;\n\nfont-family: \'Inter\';\nfont-style: normal;\nfont-weight: 400;\nfont-size: 22px;\n\ncolor: #8D8D8D;\n")
        self.mileage_field.setIconSize(QtCore.QSize(50, 80))
        self.mileage_field.setObjectName("mileage_field")
        self.fuel_field = QtWidgets.QPushButton(parent=Form)
        self.fuel_field.setGeometry(QtCore.QRect(420, 260, 365, 66))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fuel_field.setFont(font)
        self.fuel_field.setStyleSheet("background: #FFFFFF;\n\nborder: 1px solid #CDCDCD;\nborder-radius: 16px;\n\nfont-family: \'Inter\';\nfont-style: normal;\nfont-weight: 400;\nfont-size: 22px;\n\ncolor: #8D8D8D;\n")
        self.fuel_field.setIconSize(QtCore.QSize(50, 80))
        self.fuel_field.setObjectName("fuel_field")
        self.error_text = QtWidgets.QLabel(parent=Form)
        self.error_text.setGeometry(QtCore.QRect(420, 120, 365, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(15)
        self.error_text.setFont(font)
        self.error_text.setStyleSheet("color: #A6111B;")
        self.error_text.setText("")
        self.error_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_text.setObjectName("error_text")
        self.background.raise_()
        self.background2.raise_()
        self.text.raise_()
        self.car_name_field.raise_()
        self.step_text.raise_()
        self.key_zero.raise_()
        self.key_nine.raise_()
        self.key_five.raise_()
        self.key_seven.raise_()
        self.key_eight.raise_()
        self.key_two.raise_()
        self.clear_button.raise_()
        self.key_four.raise_()
        self.key_one.raise_()
        self.key_three.raise_()
        self.key_six.raise_()
        self.next_step_page.raise_()
        self.mileage_field.raise_()
        self.fuel_field.raise_()
        self.error_text.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.text.setText(_translate("Form", "Информация об автомобиле"))
        self.car_name_field.setText(_translate("Form", "CAR NAME"))
        self.step_text.setText(_translate("Form", "3/3"))
        self.key_zero.setText(_translate("Form", "0"))
        self.key_nine.setText(_translate("Form", "9"))
        self.key_five.setText(_translate("Form", "5"))
        self.key_seven.setText(_translate("Form", "7"))
        self.key_eight.setText(_translate("Form", "8"))
        self.key_two.setText(_translate("Form", "2"))
        self.key_four.setText(_translate("Form", "4"))
        self.key_one.setText(_translate("Form", "1"))
        self.key_three.setText(_translate("Form", "3"))
        self.key_six.setText(_translate("Form", "6"))
        self.next_step_page.setText(_translate("Form", "Далее"))
        self.mileage_field.setText(_translate("Form", "Текущий пробег, км"))
        self.fuel_field.setText(_translate("Form", "Остаток топлива в литрах"))
