from PyQt6 import QtCore, QtGui, QtWidgets

class info_page(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        self.text = QtWidgets.QLabel(parent=Form)
        self.text.setGeometry(QtCore.QRect(30, 24, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(24)
        self.text.setFont(font)
        self.text.setStyleSheet("")
        self.text.setLineWidth(0)
        self.text.setMidLineWidth(0)
        self.text.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.text.setIndent(-1)
        self.text.setObjectName("text")
        self.text2 = QtWidgets.QLabel(parent=Form)
        self.text2.setGeometry(QtCore.QRect(30, 71, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.text2.setFont(font)
        self.text2.setStyleSheet("color: #8D8D8D;")
        self.text2.setObjectName("text2")
        self.info = QtWidgets.QGraphicsView(parent=Form)
        self.info.setGeometry(QtCore.QRect(262, 130, 508, 208))
        self.info.setStyleSheet("background: #FFFFFF;\nborder: 3px solid #D9D9D9;\nborder-radius: 16;\n")
        self.info.setObjectName("info")
        self.decline_button = QtWidgets.QPushButton(parent=Form)
        self.decline_button.setGeometry(QtCore.QRect(30, 378, 348, 66))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.decline_button.setFont(font)
        self.decline_button.setStyleSheet("color: #A6111B;\nbackground: #FFE0E3;\nborder-radius: 16px;")
        self.decline_button.setObjectName("decline_button")
        self.photo_button = QtWidgets.QPushButton(parent=Form)
        self.photo_button.setGeometry(QtCore.QRect(30, 130, 224, 208))
        self.photo_button.setStyleSheet("background: #FFFFFF;\nborder: 3px solid #D9D9D9;\nborder-radius: 16;\n")
        self.photo_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Work/SDPO/design/img/photo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.photo_button.setIcon(icon)
        self.photo_button.setIconSize(QtCore.QSize(66, 60))
        self.photo_button.setObjectName("photo_button")
        self.date_field = QtWidgets.QLabel(parent=Form)
        self.date_field.setGeometry(QtCore.QRect(545, 231, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.date_field.setFont(font)
        self.date_field.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.date_field.setObjectName("date_field")
        self.text5 = QtWidgets.QLabel(parent=Form)
        self.text5.setGeometry(QtCore.QRect(332, 264, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.text5.setFont(font)
        self.text5.setStyleSheet("color: #8D8D8D;")
        self.text5.setObjectName("text5")
        self.background = QtWidgets.QGraphicsView(parent=Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.background.setStyleSheet("border: 0;")
        self.background.setObjectName("background")
        self.text3 = QtWidgets.QLabel(parent=Form)
        self.text3.setGeometry(QtCore.QRect(60, 349, 681, 21))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.text3.setFont(font)
        self.text3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text3.setAutoFillBackground(False)
        self.text3.setStyleSheet("color: #8D8D8D;")
        self.text3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.text3.setLineWidth(0)
        self.text3.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.text3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.text3.setWordWrap(False)
        self.text3.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.text3.setObjectName("text3")
        self.number_field = QtWidgets.QLabel(parent=Form)
        self.number_field.setGeometry(QtCore.QRect(510, 264, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.number_field.setFont(font)
        self.number_field.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.number_field.setObjectName("number_field")
        self.name_field = QtWidgets.QLabel(parent=Form)
        self.name_field.setGeometry(QtCore.QRect(262, 176, 508, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        self.name_field.setFont(font)
        self.name_field.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_field.setObjectName("name_field")
        self.next_step_button = QtWidgets.QPushButton(parent=Form)
        self.next_step_button.setGeometry(QtCore.QRect(422, 378, 348, 66))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.next_step_button.setFont(font)
        self.next_step_button.setStyleSheet("border-radius: 16;\nbackground-color:#A6111B;\ncolor: white;")
        self.next_step_button.setObjectName("next_step_button")
        self.text4 = QtWidgets.QLabel(parent=Form)
        self.text4.setGeometry(QtCore.QRect(376, 231, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.text4.setFont(font)
        self.text4.setStyleSheet("color: #8D8D8D;")
        self.text4.setObjectName("text4")
        self.skud_button = QtWidgets.QPushButton(parent=Form)
        self.skud_button.setGeometry(QtCore.QRect(494, 22, 288, 66))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.skud_button.setFont(font)
        self.skud_button.setStyleSheet("color: #A6111B;\nbackground: #FFE0E3;\nborder-radius: 16px;")
        self.skud_button.setObjectName("skud_button")
        self.background.raise_()
        self.text.raise_()
        self.text2.raise_()
        self.info.raise_()
        self.decline_button.raise_()
        self.photo_button.raise_()
        self.date_field.raise_()
        self.text5.raise_()
        self.text3.raise_()
        self.number_field.raise_()
        self.name_field.raise_()
        self.next_step_button.raise_()
        self.text4.raise_()
        self.skud_button.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.text.setText(_translate("Form", "Проверка информации"))
        self.text2.setText(_translate("Form", "Если это не ваши данные, нажмите кнопку “Это не я”"))
        self.decline_button.setText(_translate("Form", "Это не я"))
        self.date_field.setText(_translate("Form", "24.03.2000"))
        self.text5.setText(_translate("Form", "Номер телефона:"))
        self.text3.setText(_translate("Form", "Нажимая ЭТО ДЕЙСТВИТЕЛЬНО Я, Вы даете согласие на обработку Ваших персональных данных"))
        self.number_field.setText(_translate("Form", "+7 123 123 12-12"))
        self.name_field.setText(_translate("Form", "Иванов Иван Иванович"))
        self.next_step_button.setText(_translate("Form", "Сделать фото"))
        self.text4.setText(_translate("Form", "Дата рождения:"))
        self.skud_button.setText(_translate("Form", "Привязать карту СКУД"))
